/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import acceso.AdministradorDAO;
import acceso.LoginDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Administrador;
import modelo.EnumTipo;
import modelo.Login;

/**
 *
 * @author Laura
 */
public class AdminVista extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioVista
     */
    private Administrador d;
    private AdministradorDAO adao;
    
    private List<Administrador> administradores;
    
  
    
    public AdminVista() {
        initComponents();
        adao = new AdministradorDAO();
        administradores = new ArrayList<>();
        this.iniciarLista();
      
    }
    
    private void iniciarLista(){
        this.administradores=this.adao.VerAdministrador();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        for(int i = 0; i< this.administradores.size();i++){
            dtm.addRow(new Object[]{
               this.administradores.get(i).getIdAdministrador(),
                this.administradores.get(i).getNombre(),
                this.administradores.get(i).getApellido(),
                this.administradores.get(i).getCorreo(),
                this.administradores.get(i).getCelular()
            
            });
        }
        
    }
    
       private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        try{
            adao.AdministradorOff();
            System.out.println("Conexión cerrada.");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void setIdAdminValue(int idAdmin) {
        jLabel3.setText(String.valueOf(idAdmin));
    } 
      private void cargarIdAdminDesdeVista() {
    PantallaPrincipalAdmin pantallaPrincipal = new PantallaPrincipalAdmin();
    String idAdminPrincipal = pantallaPrincipal.getIdAdminPrincipal();
    jLabel3.setText(idAdminPrincipal);
}
     
    public String getIdAdminGestion() {
        return jLabel3.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregarLibro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 90, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdAdministrador", "Nombre", "Apellido", "Correo", "Celular"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 730, 180));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Gestion de Administradores");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 40));

        jButtonAgregarLibro.setText("VOLVER");
        jButtonAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarLibroActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAgregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 100, -1));

        jButton2.setText("ACTUALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jButton6.setText("AGREGAR ADMIN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksant\\Documents\\NetBeansProjects\\UsuarioBiblioteca\\UsuarioBiblioteca\\pngwing.com (4).png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 0));
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarLibroActionPerformed
    int codigo = Integer.parseInt(jLabel3.getText());
 
    // Crear una instancia de LoginDAO
    LoginDAO loginDAO = new LoginDAO();

    // Buscar el tipo de usuario en la base de datos
    Login login = loginDAO.BuscarLogin(codigo);

    // Verificar el tipo de usuario y mostrar la interfaz correspondiente
    if (login != null) {
        if (EnumTipo.Jefe.equals(login.getTIPO())) {
            // Mostrar la interfaz de administrador
            this.dispose();
            PantallaPrincipal pantalla = new PantallaPrincipal();
            pantalla.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
            pantalla.setVisible(true);
            pantalla.setIdAdminValue(codigo);
             
        } else {
            if(EnumTipo.Admin.equals(login.getTIPO())){
                this.dispose();
                PantallaPrincipalAdmin vigilante = new PantallaPrincipalAdmin();
                 vigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
                vigilante.setVisible(true);
                        
                // Captura el valor de codigo y establece en AddVigilante
                //addVigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
              //  addVigilante.setVisible(true);
                vigilante.setIdAdminValue(codigo);
       
            }
            else{
                if(EnumTipo.Vigilante.equals(login.getTIPO())){
                    this.dispose();
                PantallaPrincipalVigilante vigilante = new PantallaPrincipalVigilante(); // Reemplaza Vigilante con el nombre de tu interfaz vigilante
                vigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
                vigilante.setVisible(true);
                vigilante.setIdAdminValue(codigo);
            }
            }
            
        }
    } else {
        JOptionPane.showMessageDialog(null, "Usuario no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonAgregarLibroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
    int fila_seleccionada = jTable1.getSelectedRow();
        if(fila_seleccionada >= 0){
            int codigo = Integer.parseInt(jLabel3.getText());
            this.dispose();
           AddAdmin vista = new AddAdmin(this.administradores.get(fila_seleccionada));
           vista.setVisible(true);
           vista.setLocationRelativeTo(null);
           vista.setIdAdminValue(codigo);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una fila.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              // TODO add your handling code here:ELIMINAR
        int fila_seleccionada = jTable1.getSelectedRow();
        if(fila_seleccionada >= 0){            
            int decision = JOptionPane.showConfirmDialog(null, "Confirma que desea eliminar este admin?", "Advertencia", JOptionPane.YES_NO_OPTION);            
            if(decision == 0){
                    Administrador AdminAEliminar = this.administradores.get(fila_seleccionada);
                    this.adao.EliminarAdministrador(AdminAEliminar);
                    this.iniciarLista();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una fila.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//AGREGAR ADMIN    
        int codigo = Integer.parseInt(jLabel3.getText());
        this.dispose();
        AddAdmin disc = new AddAdmin();
        disc.setVisible(true);    
        disc.setLocationRelativeTo(null);
         disc.setIdAdminValue(codigo);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:BUSCAR
        int codigo = Integer.parseInt(jLabel3.getText());
        this.dispose();
        BuscarAdministrador vista = new BuscarAdministrador();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        vista.setIdAdminValue(codigo);
        
        
        
     
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAgregarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
