/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import acceso.VigilanteDAO;
import javax.swing.JOptionPane;
import modelo.Vigilante;



/**
 *
 * @author Laura
 */
public class BuscarVigilante extends javax.swing.JFrame {

    /**
     * Creates new form BuscarUsuarioVista
     */
        private Vigilante l;
       
    private VigilanteDAO ldao;
    
    public BuscarVigilante() {
        initComponents();
        l=null;
        ldao= new VigilanteDAO();
        cargarIdAdminDesdeVista();
       
    }
    public boolean validar(){
        boolean val=false;
            try{
                int codigo = Integer.parseInt(jTextField1.getText());
                val=true;
            }catch(NumberFormatException ex){
                val = false;
            }
      return val; 
    }
         public void setIdAdminValue(int idAdmin) {
        jLabel13.setText(String.valueOf(idAdmin));
    }
    
    private void cargarIdAdminDesdeVista() {
        VigilanteVista vigilanteVista = new VigilanteVista();
        String idAdminGestion = vigilanteVista.getIdAdminGestion();
        jLabel13.setText(idAdminGestion);
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        try{
            ldao.VigilanteOff();
            System.out.println("Conexión cerrada.");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IdVigilante = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TIPO = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        IdAdmin = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setText("BUSCAR VIGILANTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 1)); // NOI18N
        jLabel3.setText("IdVigilante");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        IdVigilante.setFont(new java.awt.Font("Segoe UI", 3, 1)); // NOI18N
        IdVigilante.setText("______________");
        jPanel1.add(IdVigilante, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 98, -1));

        Nombre.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Nombre.setText("______________");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Apellido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 1)); // NOI18N
        jLabel6.setText("TIPO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        TIPO.setFont(new java.awt.Font("Segoe UI", 3, 1)); // NOI18N
        TIPO.setText("_____________");
        jPanel1.add(TIPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        Apellido.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Apellido.setText("______________");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 120, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        jLabel2.setText("CODIGO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksant\\Documents\\NetBeansProjects\\UsuarioBiblioteca\\UsuarioBiblioteca\\pngwing.com (4).png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Correo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("IdAdmin");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/apps.61678.14234735185022408.fe2c08da-fe3f-4864-b86c-868c83f48cce.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 230, 230));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("Celular");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        Correo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Correo.setText("_____________");
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        IdAdmin.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        IdAdmin.setText("_____________");
        jPanel1.add(IdAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        Celular.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Celular.setText("_____________");
        jPanel1.add(Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // TODO add your handling code here:
               if (validar()) {
            try {
                int codigo = Integer.parseInt(jTextField1.getText());
                l = this.ldao.BuscarVigilante(codigo);

                if (l == null) {
                    JOptionPane.showMessageDialog(this, "No se encontró ningún vigilante con ese código.");
                } else {
                    IdVigilante.setText(String.valueOf(l.getIdVigilante()));
                    Apellido.setText(l.getApellido());
                    Nombre.setText(l.getNombre());
                    Correo.setText(l.getCorreo());
                    IdAdmin.setText(String.valueOf(l.getIdAdmin()));  // Convert int to String
                    Celular.setText(String.valueOf(l.getCelular()));  // Convert int to String
                    TIPO.setText(l.getTIPO().toString());
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Ingrese un valor de código válido.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al buscar al vigilante.");
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un valor de código válido.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int codigo = Integer.parseInt(jLabel13.getText());
       this.dispose();
       VigilanteVista vista = new VigilanteVista();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
         vista.setIdAdminValue(codigo);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarVigilante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel IdAdmin;
    private javax.swing.JLabel IdVigilante;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel TIPO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
