/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import acceso.AdministradorDAO;
import acceso.Conexion;
import acceso.LoginDAO;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import modelo.Administrador;
import modelo.EnumTipo;
import modelo.Vehiculo;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import gui.BuscarVehiculo;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Font.BOLD;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import static java.util.Calendar.DATE;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.border.Border;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import modelo.Login;

/**
 *
 * @author ksant
 */
public class BuscarVehiculo extends javax.swing.JFrame {
FondoPanel fondo = new FondoPanel();
    private ImageIcon imagenBahia1;
    PreparedStatement ps; //sentencia
    ResultSet rs; //resultado
    Connection aux; //conexion
    String sql;
    /**
     * Creates new form Mapa
     * @param ingresarVehiculo
     */
    public BuscarVehiculo() {
      this.setContentPane(fondo);
        initComponents();
        
         Conexion conexion = new Conexion();
        aux = conexion.conectar();
        if (aux == null) {
            // Manejar el caso en el que la conexión no se estableció correctamente
            System.out.println("Error: La conexión es nula");
        }else{
            ((AbstractDocument) PLACA.getDocument()).setDocumentFilter(new DocumentFilter() {
    private final int maxCharacters = 7;

    public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
        String currentText = fb.getDocument().getText(0, fb.getDocument().getLength());
        int futureLength = currentText.length() - length + text.length();

        if (futureLength <= maxCharacters) {
            super.replace(fb, offset, length, text, attrs);
        }
    }
});
            
        }
              
        
    }
    
       public void setIdAdminValue(int idAdmin) {
      jLabel4.setText(String.valueOf(idAdmin));
    }              
      
public String getIdAdminPrincipal() {
    return jLabel4.getText();
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new  FondoPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PLACA = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Daco_1191009.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 490, 100));

        jLabel3.setFont(new java.awt.Font("Vineta BT", 0, 24)); // NOI18N
        jLabel3.setText("¿Buscas tu vehiculo?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 450, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("INGRESA LA PLACA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, 40));

        PLACA.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        PLACA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLACAActionPerformed(evt);
            }
        });
        jPanel2.add(PLACA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 180, 60));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jLabel4.setText("0");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(751, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       int codigo = Integer.parseInt(jLabel4.getText());
       String codigo1 = jLabel4.getText();
 
    // Crear una instancia de LoginDAO
    LoginDAO loginDAO = new LoginDAO();

    // Buscar el tipo de usuario en la base de datos
    Login login = loginDAO.BuscarLogin(codigo);

    // Verificar el tipo de usuario y mostrar la interfaz correspondiente
    if (login != null) {
        if (EnumTipo.Jefe.equals(login.getTIPO())) {
            // Mostrar la interfaz de administrador
            this.dispose();
            PantallaPrincipal pantalla = new PantallaPrincipal();
            pantalla.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
            pantalla.setVisible(true);
            pantalla.setIdAdminValue(codigo);
        } else {
            if(EnumTipo.Admin.equals(login.getTIPO())){
                this.dispose();
                PantallaPrincipalAdmin vigilante = new PantallaPrincipalAdmin();
                 vigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
                vigilante.setVisible(true);
                        
                // Captura el valor de codigo y establece en AddVigilante
                //addVigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
              //  addVigilante.setVisible(true);
                vigilante.setIdAdminValue(codigo);
            }
            else{
                if(EnumTipo.Vigilante.equals(login.getTIPO())){
                    this.dispose();
                PantallaPrincipalVigilante vigilante = new PantallaPrincipalVigilante(); // Reemplaza Vigilante con el nombre de tu interfaz vigilante
                vigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
                vigilante.setVisible(true);
                 vigilante.setIdAdminValue(codigo);
            }
      
            }      
        }
    } else {
         this.dispose();
         LoginPrincipal vigilante = new LoginPrincipal(); // Reemplaza Vigilante con el nombre de tu interfaz vigilante
                vigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
                vigilante.setVisible(true);
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PLACAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLACAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PLACAActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      String placa = PLACA.getText();

    // Consulta SQL para obtener la bahía basada en la placa
    String consulta = "SELECT Bahia FROM vehiculo WHERE Placa = ?";
    
    try {
        // Preparar la declaración SQL con el parámetro
        ps = aux.prepareStatement(consulta);
        ps.setString(1, placa);

        // Ejecutar la consulta
        rs = ps.executeQuery();

        if (rs.next()) {
            // Si se encuentra un resultado, obtener el valor de la bahía
            int bahia = rs.getInt("Bahia");
            
            // Crear un JLabel personalizado con un tamaño de fuente más grande
            JLabel label = new JLabel("La bahía para la placa " + placa + " es: " + bahia);
            label.setFont(new Font("Arial", Font.PLAIN, 25));

            // Mostrar el JOptionPane con el JLabel personalizado
            JOptionPane.showMessageDialog(this, label, "Resultado de la búsqueda", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Si no se encuentra ningún resultado, mostrar un mensaje
            JOptionPane.showMessageDialog(this, "No se encontró información para la placa " + placa, "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        // Manejar cualquier error de SQL
        JOptionPane.showMessageDialog(this, "Error al buscar en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Cerrar la conexión, el statement y el resultado
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PLACA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
