/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import acceso.AdministradorDAO;
import acceso.LoginDAO;
import acceso.VehiculoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Administrador;
import modelo.EnumTipo;
import modelo.Login;
import modelo.Vehiculo;
import modelo.Vigilante;

/**
 *
 * @author Laura
 */
public class ListarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioVista
     */
    private Vehiculo d;
    private VehiculoDAO adao;
    
    private List<Vehiculo> vehiculos;
    
  
    
    public ListarVehiculo() {
        initComponents();
        adao = new VehiculoDAO();
        vehiculos = new ArrayList<>();
        this.iniciarLista();
      
    }
       public void setIdAdminValue(int idAdmin) {
      jLabel3.setText(String.valueOf(idAdmin));
    }              
      
public String getIdAdminPrincipal() {
    return jLabel3.getText();
}
    
    private void iniciarLista(){
        this.vehiculos=this.adao.VerVehiculo();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        for(int i = 0; i< this.vehiculos.size();i++){
            dtm.addRow(new Object[]{
               this.vehiculos.get(i).getPlaca(),
                this.vehiculos.get(i).getNombreUsuario(),
                this.vehiculos.get(i).getBahia(),
                this.vehiculos.get(i).getEnumVehiculo(),
                this.vehiculos.get(i).getHoraEntrada(),
                this.vehiculos.get(i).getEstado()
            
            });
        }
        
    }
    
       private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        try{
            adao.VehiculoOff();
            System.out.println("Conexión cerrada.");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregarLibro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Propietario", "Bahia", "Tipo Vehiculo", "HoraEntrada"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 610, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Registro de Vehiculos");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 490, 70));

        jButtonAgregarLibro.setText("VOLVER");
        jButtonAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarLibroActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAgregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksant\\Documents\\NetBeansProjects\\UsuarioBiblioteca\\UsuarioBiblioteca\\pngwing.com (4).png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 650, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarLibroActionPerformed
   int codigo = Integer.parseInt(jLabel3.getText());
 
    // Crear una instancia de LoginDAO
    LoginDAO loginDAO = new LoginDAO();

    // Buscar el tipo de usuario en la base de datos
    Login login = loginDAO.BuscarLogin(codigo);

    // Verificar el tipo de usuario y mostrar la interfaz correspondiente
    if (login != null) {
        if (EnumTipo.Jefe.equals(login.getTIPO())) {
            // Mostrar la interfaz de administrador
            this.dispose();
            InterfazVehiculo pantalla = new InterfazVehiculo();
            pantalla.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
            pantalla.setVisible(true);
           pantalla.setIdAdminValue(codigo);
        } else {
            if(EnumTipo.Admin.equals(login.getTIPO())){
                this.dispose();
               InterfazVehiculo vigilante = new InterfazVehiculo();
                 vigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
                vigilante.setVisible(true);
                        
                // Captura el valor de codigo y establece en AddVigilante
                //addVigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
              //  addVigilante.setVisible(true);
                vigilante.setIdAdminValue(codigo);
       
            }
            else{
                if(EnumTipo.Vigilante.equals(login.getTIPO())){
                    this.dispose();
                PantallaPrincipalVigilante vigilante = new PantallaPrincipalVigilante(); // Reemplaza Vigilante con el nombre de tu interfaz vigilante
                vigilante.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
                vigilante.setVisible(true);
                vigilante.setIdAdminValue(codigo);
            }
            }
            
        }
    } else {
        JOptionPane.showMessageDialog(null, "Usuario no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
    }
       

    }//GEN-LAST:event_jButtonAgregarLibroActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:BUSCAR
        this.dispose();
        BuscarAdministrador vista = new BuscarAdministrador();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAgregarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
